janken_time/base/urls.py
from django.urls import path
from . import views
from django.conf import settings # 追記箇所(3～4行目)
from django.conf.urls.static import static


app_name = 'base'

urlpatterns = [
    path('edit_page/', views.edit_page, name='edit_page'), # 追記箇所(13～14行目)
    path('self_profile/', views.self_profile, name='self_profile'),

    # path('base/', views.reviewbase, name='base'),
    path('', views.index, name='index'),
    path('settings/', views.settings, name='settings'),
    path('picked/', views.pickedview, name='picked'),
    path('donation/', views.simpleCheckout, name='donation'),
    path('complete/', views.paymentComplete, name='complete'),
    path('exec-ajax/', views.exec, name='exec_ajax'),
    path('ajax-number/', views.ajax_number, name='ajax_number'),

    path('champion_list/', views.champion, name='champion_list'),
    path('add_champion/', views.AddChampion.as_view(), name='add_champion'),
    path('champion_detail/<int:pk>/', views.ChampionDetail.as_view(), name="champion_detail"),
    path('champion_refresh/', views.refresh, name='champion_refresh'),
    path('champion_update/<int:pk>/', views.ChampionUpdate.as_view(), name="champion_update"),
    path('champion_delete/<int:pk>/', views.ChampionDelete.as_view(), name='champion_delete'),
    # path('champion_category/<str:category>/', views.CategoryView.as_view(), name='champion_category'),
    path('champion_category/<str:category>/', views.category, name='champion_category'),
]

if settings.DEBUG: # 以下追記箇所
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

janken_time/board_app/urls.py
from django.urls import path
from . import views
from django.conf import settings # 追記箇所(3～4行目)
from django.conf.urls.static import static

app_name = 'board_app'

urlpatterns = [
  path('create_topic/', views.create_topic, name='create_topic'),
  path('list_topics/', views.list_topics, name='list_topics'), # 追記箇所
  path('edit_topic/<int:id>', views.edit_topic, name='edit_topic'), # 追記箇所
  path('delete_topic/<int:id>', views.delete_topic, name='delete_topic'), # 追記箇所
  path('post_texts/<int:topic_id>/', views.post_texts, name='post_texts'),
  path('save_text', views.save_text, name='save_text'),
  path('profile/<int:user_id>', views.profile, name="profile"),
  path('ranking/<str:rule>/', views.ranking, name="ranking"),
]

if settings.DEBUG: # 以下追記箇所
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

janken_time/janken_time/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('accounts/', include('allauth.urls')),
    path('board_app/', include('board_app.urls')),
]

janken_time/base/views/champion_views.py
from django.shortcuts import render, redirect
from base.models import Champion, CustomUser, Category
from django.http import JsonResponse
# from . import winners
import json
# from rest_framework import serializers
from django.core import serializers
from django.contrib.auth.decorators import login_required
import random
# Create your views here.
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.urls import reverse
from django.views import View
from django.db.models import Q



def simpleCheckout(request):
    return render(request, 'base/donation.html')

def paymentComplete(request):
    if request.method == 'POST':
        try:
            body = json.loads(request.body)
        except Exception:
            pass
        
        amount = body['amount']
        print(body)
        user_id = body['user_id']
        user = CustomUser.objects.get(id=user_id)
        user.donations += float(amount)
        user.save()
        print('context代入前')
        context = {'amount': amount}
        # context = {'amount': 5.00 }
        print('context代入後')
    return render(request, 'base/complete.html')
    #return redirect('base:complete')
    # return JsonResponse('hello',safe=False)



# def reviewbase(request):
#     return render(request, 'base.html')


def index(request):
    return render(request, 'index.html')


def settings(request):
    champions = Champion.objects.all()
    context = {'champions': champions}
    return render(request, 'base/settings.html', context)

def champion(request):
    champions = Champion.objects.all()
    keyword = request.GET.get('search_form')
    if keyword:
      keyword = keyword.split()
      for k in keyword:
        champions = champions.filter(
                    Q(name__icontains=k) |
                    Q(description__icontains=k) |
                    Q(category__name__icontains=k)
                  )
    print(champions.query)
    champions = champions.distinct()
    print(champions)
    context = {'champions': champions}
    return render(request, 'base/champion_list.html', context)

def category(request, category):
    category_data = Category.objects.get(name=category)
    champions = Champion.objects.filter(category=category_data)
    print(champions)
    context = {'champions': champions}
    return render(request, 'base/champion_list.html', context)

class CategoryView(View):
    def get(self, request, *args, **kwargs):
        category_data = Category.objects.get(name=self.kwargs['category'])
        champion = Champion.objects.filter(category=category_data)
        context = {'champion': champion}
        return render(request, 'base/champion_list.html', context)


class AddChampion(CreateView):
    template_name = 'base/add_champion.html'
    model = Champion
    fields = ('name', 'category', 'picture', 'description')
    success_url = reverse_lazy('base:champion_list')


class ChampionDetail(DetailView):
    #Championテーブル連携
    model = Champion
    #レコード情報をテンプレートに渡すオブジェクト
    context_object_name = "champion"
    #テンプレートファイル連携
    template_name = "base/champion_detail.html"



class ChampionUpdate(UpdateView):
    template_name = 'base/champion_update.html'
    model = Champion
    fields = ['name', 'category', 'picture', 'description']

    def get_success_url(self):
        return reverse('base:champion_detail', kwargs={'pk': self.object.pk})


class ChampionDelete(DeleteView):
    template_name = 'base/champion_delete.html'
    model = Champion

    success_url = reverse_lazy('base:champion_list')




def pickedview(request):
    if request.method == 'POST':
        results = request.POST.getlist("champion")
        user = CustomUser.objects.get(id=request.user.id)
        print(results)
        result_list = []
        CustomUser.champions.through.objects.filter(customuser_id=request.user.id).delete()
        for i in results:
            result_list.append(Champion.objects.get(id=i))
            print(i)
            user.champions.add(Champion.objects.get(id=i))
        # print(dir(user.champions))
        print(user.champions)
        user.champions.update()
        print(result_list)
        champ_list = []
        for i in user.champions.all():
            champ_list.append(i)
        context = {'champions': champ_list}
    else:
        user = CustomUser.objects.get(id=request.user.id)
        champ_list = []
        for i in user.champions.all():
            champ_list.append(i)
        context = {'champions': champ_list}

    return render(request, 'base/picked.html', context)

def refresh(request):
    CustomUser.champions.through.objects.filter(customuser_id=request.user.id).delete()
    return redirect('base:picked')

janken_time/base/views/janken_views.py
from django.shortcuts import render, redirect
from base.models import Champion, CustomUser, Category, Enemy
from django.http import JsonResponse
from base import winners
import json
# from rest_framework import serializers
from django.core import serializers
from django.contrib.auth.decorators import login_required
import random
# Create your views here.


class User:
    name = None
    hand = 0
    is_user = True

class PC:
    name = None
    hand = 0
    is_user = False


def hand_func():
    hand = random.randint(0, 2)
    return hand



# Ajax Ajax Ajax Ajax Ajax Ajax Ajax Ajax Ajax Ajax Ajax Ajax Ajax Ajax Ajax Ajax Ajax
@login_required
def exec(request):
    picked = CustomUser.champions.through.objects.filter(customuser_id=request.user.id)
    picked_list = []
    for i in picked:
        picked_list.append(i.champion_id)
    show_list = []
    for i in picked_list:
        show_list.append(Champion.objects.get(id=i))
    
    show_champions = show_list
    '''
    敵機作成
    '''
    enemies = Enemy.objects.order_by('?')[:3]
    print('***enemies')
    show_enemies = []
    for i in enemies:
        show_enemies.append(i)

    print(enemies)


    context = {'show_champions': show_champions, 'enemies': show_enemies}
    # sessionを削除しておく
    if 'user_list' in request.session:
        del request.session['user_list']
    if 'pc_list' in request.session:
        del request.session['pc_list']
    if 'index_number' in request.session:
        del request.session['number_index']
    if 'user_stable_list' in request.session:
        del request.session['user_stable_list']
    '''
    # session PCリストの作成
    '''
    pc_name_list = ['Enemy1', 'Enemy2', 'Enemy3']
    pc_list = ['enemy1', 'enemy2', 'enemy3']
    for i in range(len(pc_list)):
        pc=PC()
        pc.name=pc_name_list[i]
        pc.hand=hand_func()
        pc_list[i] = json.dumps(pc.__dict__)

    
    print(pc_list)
    # print(pc_hand_list)
    # request.session['pc_list'] = serializers.serialize('json', pc_list)
    request.session['pc_list'] = pc_list
    # print(request.session['pc_list'])
    # print(serializers.json.Deserializer(request.session['pc_list']))
    # pc_gen = serializers.json.Deserializer(request.session['pc_list'])
    # print(pc_gen)
    # for i in list(pc_gen):
    #     print(i)
    # pc_gen_list = list(pc_gen)
    # print(pc_gen_list)
    # for i in pc_gen_list:
    #     print(i)
    '''
    # session ユーザーのキャラリストとそのidリストの作成
    '''
    user = CustomUser.objects.get(id=request.user.id)
    user_list = []
    user_id_list = []
    # デフォルトのユーザーのキャラとそのidをリストで取得
    for i in user.champions.all():
        user_obj = User()
        user_obj.name = i.name
        user_list.append(json.dumps(user_obj.__dict__))
        user_id_list.append(i.id)
    print(user_list)
    print(user_id_list)
    request.session['user_list'] = user_list
    request.session['user_stable_list'] = user_list
    # request.session['user_list'] = serializers.serialize('json', user_list)
    # request.session['user_id_list'] = user_id_list

    # player_list = user_list + pc_list
    # request.session['player_list'] = player_list
    number_index = []
    for i in range(len(user_list)):
        number_index.append(i+1)
    request.session['number_index'] = number_index
    print(number_index)


    return render(request, 'base/exec_ajax.html', context)



def ajax_number(request):
    if request.POST.get('number1'):
       number1 = int(request.POST.get('number1'))
    if request.POST.get('number2'):
        number2 = int(request.POST.get('number2'))
    if request.POST.get('number3'):
        number3 = int(request.POST.get('number3'))
    print('***number1,number2,number3')
    print(request.POST.get('number1'))
    print(request.POST.get('number2'))
    print(request.POST.get('number3'))
    # if request.POST.get('number1') == None and request.POST.get('number2') == None and request.POST.get('number3') == None:
    #     number1 = 1
    #     number2 = 1
    #     number3 = 0
    # plus = number1 + number2 + number3
    '''
    テスト開始
    '''
    '''
    # session deserialize PCインスタンスをsessionから取得 オブジェクトのリストを作成
    手はここで入力するようにする。
    '''
    pc_gen = request.session['pc_list']
    print('***pc_gen')
    print(pc_gen)
    # テスト
    pc_hand_list = []
    pc_chara_list = []

    for i in pc_gen:
        print(i)
        pc_dict = json.loads(i)
        print(pc_dict['name'])
        pc = PC()
        pc.name = pc_dict['name']
        pc.hand = hand_func()
        # pc.hand = 1
        pc_hand_list.append(pc.hand)
        pc_chara_list.append(pc)


    # pc_gen = serializers.json.Deserializer(request.session['pc_list'])
    # print(pc_gen)
    # for i in list(pc_gen):
    #     i.object.hand = hand_func()
    #     print(i)
    #     pc_hand_list.append(i.object.hand)
    #     pc_chara_list.append(i)
        
    print(pc_hand_list)
    print(pc_chara_list)

    # for i in range(len(pc_json_list)):
    #     pc_dict=json.loads(pc_json_list[i])
    #     pc=PC()
    #     pc.name=pc_dict['name']
    #     pc.hand=pc_dict['hand']
    #     # pc_list[i].hand = pc_list[i].hand_func()
    #     pc_hand_list.append(pc.hand)
    # print(pc_hand_list)
    '''
    # session deserialize sessionからUserのキャラを取得し、オブジェクトのリストを作成　
    # 手を入力
    '''
    user = CustomUser.objects.get(id=request.user.id)
    # 入力情報をリスト化
    # if number1+1 and number2+1 and number3+1:
    #     number_list = [number1, number2, number3]
    # elif number1+1 and number2+1:
    #     number_list = [number1, number2]
    # elif number2+1 and number3+1:
    #     number_list = [number2, number3]
    # elif number1+1 and number3+1:
    #     number_list = [number1, number3]
    # elif number1+1:
    #     number_list = [number1]
    # elif number2+1:
    #     number_list = [number2]
    # elif number3+1:
    #     number_list = [number3]
    if 'number1' in locals() and 'number2' in locals() and 'number3' in locals():
        number_list = [number1, number2, number3]
    elif 'number1' in locals() and 'number2' in locals():
        number_list = [number1, number2]
    elif 'number2' in locals() and 'number3' in locals():
        number_list = [number2, number3]
    elif 'number1' in locals() and 'number3' in locals():
        number_list = [number1, number3]
    elif 'number1' in locals():
        number_list = [number1]
    elif 'number2' in locals():
        number_list = [number2]
    elif 'number3' in locals():
        number_list = [number3]
    print('***number_list')
    print(number_list)
    # デフォルトのユーザーのキャラとそのidをリストで取得
    print('***user_list session')
    print(request.session['user_list'])
    print('***user_list session type')
    print(type(request.session['user_list']))
    # user_json_list = request.session['user_list']
    # user_json_list = serializers.deserialize('json', request.session['user_list'])
    # user_gen = serializers.json.Deserializer(request.session['user_list'])
    user_gen = request.session['user_list']
    # print(user_json_list)

    chara_list = []

    for i in user_gen:
        print(i)
        user_dict = json.loads(i)
        print(user_dict['name'])
        # print(user_dict['hand'])
        user_obj = User()
        user_obj.name = user_dict['name']
        # user_obj.hand = user_dict['hand']
        # chara_hand_list.append(user_obj.hand)
        chara_list.append(user_obj)
    print('***chara_list')
    print(chara_list)
    user_hand_list = []
    # if 'index_number' in request.session:
    #     index_number = request.session['index_number']
    #     j = 0
    #     for i in index_number:
    #         chara_list[j].hand = number_list[i]
    #         user_hand_list.append(chara_list[i].hand)
    #         j += 1
    # else:
    #     for i in range(len(chara_list)):
    #         chara_list[i].hand = number_list[i]
    #         user_hand_list.append(chara_list[i].hand)

    # for i in range(len(chara_list)):
    #     chara_list[i].hand = number_list[i]
    #     user_hand_list.append(chara_list[i].hand)
    index_number = []
    print('***session number_index')
    print(request.session['number_index'])
    for i in request.session['number_index']:
        index_number.append(i-1)    
    j = 0
    for i in index_number:
        chara_list[j].hand = number_list[i]
        user_hand_list.append(chara_list[j].hand)
        j += 1
    print('***user_hand_list')
    print(user_hand_list)
    # セッションでユーザーのキャラのhand_list作成 セッションテスト
    # request.session['user_hand_list'] = user_hand_list
    player_hand_list = user_hand_list + pc_hand_list
    print('***player_hand_list')
    print(player_hand_list)
    player_list = chara_list + pc_chara_list
    print('***player_list')
    print(player_list)
    '''
    手ラベリング
    '''
    hand_type = ['ぐー', 'ちょき', 'ぱー']
    player_hand_type = []

    for i in range(len(player_list)):
        print('{}さんは {}'.format(player_list[i].name, hand_type[player_list[i].hand]))
        player_hand_type.append(player_list[i].name + ':' + hand_type[player_list[i].hand])
    
    hand_msg = ', '.join(player_hand_type)

    '''
    じゃんけん勝ち負け判定アルゴリズム
    '''
    winner_player_list = []
    if player_hand_list.count(0) != 0 and player_hand_list.count(1) != 0 and player_hand_list.count(2) != 0:
        print('あいこ')
        result_msg = 'あいこ'
        winner_player_list = player_list.copy()
    elif player_hand_list.count(0) == len(player_hand_list) or player_hand_list.count(1) == len(player_hand_list) or player_hand_list.count(2) == len(
            player_hand_list):
        print('あいこ')
        result_msg = 'あいこ'
        winner_player_list = player_list.copy()
    elif 0 in player_hand_list and 1 in player_hand_list:
        print(winners.list_pickup(player_hand_list, 0))
        result_list = []
        print('勝利者は、')
        for i in winners.list_pickup(player_hand_list, 0):
            print(player_list[i].name, end='さん ')
            result_list.append(player_list[i].name)
        print('\nです。')

janken_time/base/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}{% endblock %}</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        {% comment %} <link href="css/styles.css" rel="stylesheet" /> {% endcomment %}

        {% comment %} <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet"> {% endcomment %}

        {% comment %} <link href="{% static 'css/one-page-wonder.min.css' %}" rel="stylesheet"> {% endcomment %}
        <link rel= "stylesheet" href="{% static 'css/styles.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css' %}">
        {% block head %}{% endblock %}
    </head>
    
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-BWEXXF8TR6"></script>
    <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'G-BWEXXF8TR6');
    </script>

    <body id="page-top">
        <div id="wrapper">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
            <div class="container px-5">
                <a class="navbar-brand" href="{% url 'base:index' %}">JANKEN TIME</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item {% block active_donation %}{% endblock %}">
                            <a class="nav-link" href="{% url 'base:donation' %}">Donation</a>
                        </li>
                        <li class="nav-item {% block active_ranking %}{% endblock %}">
                            <a class="nav-link" href="{% url 'board_app:ranking' rule='wins' %}">Ranking</a>
                        </li>
                        <li class="nav-item {% block active_list_topics %}{% endblock %}">
                            <a class="nav-link" href="{% url 'board_app:list_topics' %}">1CHAN</a>
                        </li>
                        <li class="nav-item {% block active_game%}{% endblock %}">
                            <a class="nav-link" href="{% url 'base:exec_ajax' %}">Game</a>
                        </li>
                        <li class="nav-item {% block active_champion%}{% endblock %}">
                            <a class="nav-link" href="{% url 'base:champion_list' %}">Champion</a>
                        </li>
                        {% if user.is_authenticated %}
                        <li class="nav-item {% block active_picked%}{% endblock %}">
                            <a class="nav-link" href="{% url 'base:picked' %}">Picked</a>
                        </li>
                        <li class="nav-item {% block active_pick%}{% endblock %}">
                            <a class="nav-link" href="{% url 'base:settings' %}">Pick</a>
                        </li>
                        <li class="nav-item {% block active_profile%}{% endblock %}">
                            <a class="nav-link" href="{% url 'base:self_profile' %}">Profile</a>
                            {% comment %} <a class="nav-link" href="#">Profile</a> {% endcomment %}
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account_logout' %}">Log Out</a>
                        </li>
                        {% else %}
                        <li class="nav-item {% block active_signup %}{% endblock %}">
                            <a class="nav-link" href="{% url 'account_signup' %}">Sign Up</a>
                        </li>
                        <li class="nav-item {% block active_login %}{% endblock %}">
                            <a class="nav-link" href="{% url 'account_login' %}">Log In</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        {% block header %}{% endblock %}

        {% block contents %}{% endblock %}
        <!-- Header-->
        <!-- Content section 1-->
        <!-- Content section 2-->
        <!-- Content section 3-->
        <!-- Footer-->
        <footer class="py-5 bg-black">
            <div class="container px-5"><p class="m-0 text-center text-white small">Copyright &copy; Your Website {% now 'Y' %}</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </div>
    </body>
    {% block scripts %}{% endblock %}
</html>

janken_time/base/templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %}主要ChampionをPickしてじゃんけん{% endblock %}

{% block header %}

<header class="masthead text-center text-white">
    <div class="masthead-content">
        <div class="container px-5">
            <h1 class="masthead-heading mb-0">Janken Pon</h1>
            <h2 class="masthead-subheading mb-0">Pick your champs and try janken</h2>
            {% if user.is_authenticated %}
            <a class="btn btn-primary btn-xl rounded-pill mt-5" href="{% url 'base:donation' %}">DONATION</a>
            {% else %}
            <a class="btn btn-primary btn-xl rounded-pill mt-5" href="{% url 'account_login' %}">LOG IN</a>
            {% endif %}
        </div>
    </div>
    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div>
    <div class="bg-circle-4 bg-circle"></div>
</header>

{% endblock %}

{% block contents %}

<section id="scroll">
    <div class="container px-5">
        <div class="row gx-5 align-items-center">
            <div class="col-lg-6 order-lg-2">
                <div class="p-5"><img class="img-fluid rounded-circle" src="{% static 'img/01.jpg' %}" alt="..." /></div>
            </div>
            <div class="col-lg-6 order-lg-1">
                <div class="p-5">
                    <h2 class="display-4">For those about to be a challenger...</h2>
                    <p>let's do janken match against PC player.</p>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Content section 2-->
<section>
    <div class="container px-5">
        <div class="row gx-5 align-items-center">
            <div class="col-lg-6">
                <div class="p-5"><img class="img-fluid rounded-circle" src="{% static 'img/02.jpg' %}" alt="..." /></div>
            </div>
            <div class="col-lg-6">
                <div class="p-5">
                    <h2 class="display-4">We salute you!</h2>
                    <p>All your passion compliment you, make it better.</p>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Content section 3-->
<section>
    <div class="container px-5">
        <div class="row gx-5 align-items-center">
            <div class="col-lg-6 order-lg-2">
                <div class="p-5"><img class="img-fluid rounded-circle" src="{% static 'img/03.jpg' %}" alt="..." /></div>
            </div>
            <div class="col-lg-6 order-lg-1">
                <div class="p-5">
                    <h2 class="display-4">Please Donate!</h2>
                    <p>We are supporting your challenges!Please donate to our activities and developments for the better user experience!!</p>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}