visitors_card_dev/register/urls.py
from django.urls import path
from . import views

app_name = 'register'

urlpatterns = [
    path('', views.Top.as_view(), name='top'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('user_create/', views.UserCreate.as_view(), name='user_create'),
    path('user_create/done/', views.UserCreateDone.as_view(), name='user_create_done'),
    path('user_create/complete/<token>/', views.UserCreateComplete.as_view(), name='user_create_complete'),
    path('user_detail/<int:pk>/', views.UserDetail.as_view(), name='user_detail'),
    path('user_update/<int:pk>/', views.UserUpdate.as_view(), name='user_update'),
    path('password_change/', views.PasswordChange.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'),
    path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password_reset/complete/', views.PasswordResetComplete.as_view(), name='password_reset_complete'),
    path('email/change/', views.EmailChange.as_view(), name='email_change'),
    path('email/change/done/', views.EmailChangeDone.as_view(), name='email_change_done'),
    path('email/change/complete/<str:token>/', views.EmailChangeComplete.as_view(), name='email_change_complete'),
]

visitors_card_dev/visitors_card_app/urls.py
from django.urls import path
from . import views

app_name = 'visitors_card_app'

urlpatterns = [
    path('index/', views.index, name='index'),
    # 入力フォーム
    path('welcome/', views.welcome, name='welcome'),
    path('welcome_widget/', views.welcome_widget, name='welcome_widget'),
    path('confirm/', views.confirm, name='confirm'),
    path('thankyou/', views.sent, name='sent'),
    # 情報閲覧管理者画面
    path('history/<int:page>/', views.history, name='history'),
    path('history/1/', views.history, name='history_default'),
    path('detail/<int:pk>/', views.detail, name='detail'),
    path('confirm_contact/<int:pk>/', views.confirm_contact, name='confirm_contact'),
    path('sent_contact/<int:pk>/', views.sent_contact, name='sent_contact'),

    path('update_visitors/<int:pk>/', views.VisitorsUpdate.as_view(), name='update_visitors'),
    path('update_contact/<int:pk>/<int:id>/', views.ContactUpdate.as_view(), name='update_contact'),
    # path('update_contact_all/<int:pk>/', views.VisitorsContactUpdateFormSetView.as_view(), name='update_contact_all'),
    path('update_allpost/<int:pk>/', views.update_allpost, name='update_allpost'),

    path('delete_contact/<int:pk>/', views.ContactDelete.as_view(), name='delete_contact'),
    path('delete_contact_all/<int:pk>/', views.VisitorsDelete.as_view(), name='delete_contact_all'),

    # 集計情報メニューのpath
    path('analysis_index/', views.analysis_index, name='analysis_index'),
    path('list_company/', views.list_company, name='list_company'),
    path('list_name/', views.list_name, name='list_name'),
    path('list_interviewer/', views.list_interviewer, name='list_interviewer'),
    path('list_history/', views.list_history, name='list_history'),
]

visitors_card_dev/visitors_card_dev/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('register.urls')),
    path('', include('visitors_card_app.urls')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

visitors_card_dev/visitors_card_app/views/analysis_views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

@login_required
def list_company(request):
    return render(request, 'visitors_card_app/analysis/list_company.html')

@login_required
def list_name(request):
    return render(request, 'visitors_card_app/analysis/list_name.html')

@login_required
def list_interviewer(request):
    return render(request, 'visitors_card_app/analysis/list_interviewer.html')

@login_required
def list_history(request):
    return render(request, 'visitors_card_app/analysis/list_history.html')

visitors_card_dev/visitors_card_app/views/create_read_views.py
from turtle import position
from django.shortcuts import get_object_or_404, render
from ..models import *
from django.urls import reverse_lazy
from ..forms import ContactForm, MemberForm, VisitorsForm
from django.views.generic import UpdateView, DeleteView
from django import forms
from django.shortcuts import redirect
from django.contrib import messages
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage
from django.contrib.auth.decorators import login_required

# Create your views here.

def index(request):
    context = {
        'msg': 'Hello, world!!',
    }
    return render(request, 'visitors_card_app/index.html', context)


def welcome(request):
    context = {
        'msg': 'ようこそ！！'
    }
    return render(request, 'visitors_card_app/entry_form/welcome.html', context)

def welcome_widget(request):
    form = VisitorsForm()
    # print(form)
    # print(dir(form))
    context = {
        'form': form,
    }
    return render(request, 'visitors_card_app/entry_form/welcome_widget.html', context)


def confirm(request):
    if request.method == 'POST':
        context = {
            'date': request.POST.get('date'),
            'time': request.POST.get('time'),
            'company_name': request.POST.get('company_name'),
            'visitor_name': request.POST.get('visitor_name'),
            'temperature': request.POST.get('temperature'),
            'accompany1_name': request.POST.get('accompany1_name'),
            'accompany1_temp': request.POST.get('accompany1_temp'),
            'accompany2_name': request.POST.get('accompany2_name'),
            'accompany2_temp': request.POST.get('accompany2_temp'),
            'accompany3_name': request.POST.get('accompany3_name'),
            'accompany3_temp': request.POST.get('accompany3_temp'),
            'position': request.POST.get('position'),
            'interviewer': request.POST.get('interviewer'),
            'content': request.POST.get('content'),
        }
    return render(request, 'visitors_card_app/confirm.html', context)


def sent(request):
    if request.method == 'POST':
        date = request.POST.get('date')
        time = request.POST.get('time')
        company_name = request.POST.get('company_name')
        visitor_name = request.POST.get('visitor_name')
        temperature = request.POST.get('temperature')
        accompany1_name = request.POST.get('accompany1_name')
        accompany1_temp = request.POST.get('accompany1_temp')
        accompany2_name = request.POST.get('accompany2_name')
        accompany2_temp = request.POST.get('accompany2_temp')
        accompany3_name = request.POST.get('accompany3_name')
        accompany3_temp = request.POST.get('accompany3_temp')
        position = request.POST.get('position')
        interviewer = request.POST.get('interviewer')
        content = request.POST.get('content')

        Visitors.objects.create(date=date, time=time, company_name=company_name, visitor_name=visitor_name,
        temperature=temperature, accompany1_name=accompany1_name, accompany1_temp=accompany1_temp, accompany2_name=accompany2_name,
        accompany2_temp=accompany2_temp, accompany3_name=accompany3_name, accompany3_temp=accompany3_temp, position=position,
        interviewer=interviewer, content=content)
    return render(request, 'visitors_card_app/lazy/thankyou.html')


@login_required
def history(request, page=1):
    visitors = Visitors.objects.all().order_by('-id')
    contact_objects = Contact.objects.all()
    interviewer = Member.objects.all()
    posts = Post.objects.all()


    """
    検索機能　SearchForm
    """
    if request.method == 'POST':
        print('history POST method')
        keyword = request.POST.get('search_form')
        if keyword:
            posted_visitors = visitors
            posted_interviewer = interviewer
            posted_contact_objects = contact_objects
            keyword = keyword.split()
            for k in keyword:
                visitors = visitors.filter(
                            Q(date__icontains=k) |
                            Q(time__icontains=k) |
                            Q(company_name__icontains=k) |
                            Q(visitor_name__icontains=k) |
                            Q(temperature__icontains=k) |
                            Q(accompany1_name__icontains=k) |
                            Q(accompany1_temp__icontains=k) |
                            Q(accompany2_name__icontains=k) |
                            Q(accompany2_temp__icontains=k) |
                            Q(accompany3_name__icontains=k) |
                            Q(accompany3_temp__icontains=k) |
                            Q(position__icontains=k) |
                            Q(interviewer__icontains=k) |
                            Q(content__icontains=k)
                            # Q(contact__interviewer__post__icontains=k) |
                            # Q(contact__interviewer__name__icontains=k) |
                            # Q(contact__time__icontains=k) |
                            # Q(contact__contents__icontains=k)
                )
                contact_objects = contact_objects.filter(
                        # Q(interviewer_name__icontains=k) |
                        # Q(interviewer_post__icontains=k) |
                        Q(time__icontains=k) |
                        Q(contents__icontains=k)
                    )
                interviewer = interviewer.filter(
                    name=k
                )
                posts = posts.filter(
                    name=k
                )

            if posts:
                print('if posts')
                print(posts)
                list_of_ids = set([post.pk for post in posts])
                interviewer |= posted_interviewer.filter(post_id__in=list_of_ids)
                print('if posts')
                print(interviewer)
            
            if interviewer:
                print('if interviewer')
                print(interviewer)
                list_of_ids = set([interviewer_object.pk for interviewer_object in interviewer])
                print(list_of_ids)
                list_of_ids = list(list_of_ids)
                print(list_of_ids)
                contact_objects |= posted_contact_objects.filter(interviewer_id__in=list_of_ids)
                print('if interviewer')
                print(contact_objects)
            
            if contact_objects:
                print('if contact_objects')
                print(contact_objects)
                list_of_ids = set([contact_object.contact.pk for contact_object in contact_objects])
                print(list_of_ids)
                visitors |= posted_visitors.filter(id__in=list_of_ids)


                # print('if contact_objects')
                # print(visitors)
                # print('Contact contact テスト')
                # test_obj = Contact.objects.filter(contents__icontains='緑茶')[0]
                # print(test_obj.contact.pk)
                # test_visitor = Visitors.objects.filter(id=test_obj.contact.pk)
                # print(test_visitor)
                # print('Contact contact テスト2')
                # test_list = [test_obj.contact.pk]
                # print(test_list)
                # test_visitor2 = Visitors.objects.filter(id__in=test_list)
                # print(test_visitor2)
        visitors = visitors.distinct()
        print(visitors)
    """
    検索機能ここまで
    """
    """
    ページネーション
    """
    paginator = Paginator(visitors, 8)

    try:
        visitors = paginator.page(page)
    except EmptyPage:
        visitors = paginator.page(paginator.num_pages)

    # visitor2 = Visitors.objects.get(id=2)
    # print(dir(visitor2.contact))
    context = {
        'visitors': visitors,
    }

    """
    集計情報に向けたテスト
    """
    # visitor_type = Visitors.objects.all().values_list('visitor_name', flat=True).order_by('visitor_name').distinct()
    # print(visitor_type)
    # visitor_type1 = visitor_type.get(visitor_name='小川')
    # print(visitor_type1)

    return render(request, 'visitors_card_app/history.html', context)


def detail(request, pk):
    visitor = Visitors.objects.get(pk=pk)
    print(visitor.is_contacted)
    if visitor.is_contacted:
        # contact = visitor.contact_set.all()
        contact = Contact.objects.filter(contact__pk=pk)[0]
        context = {
            'visitor': visitor,
            'contact': contact,
        }
        print(contact)
    else:
        form = MemberForm()
        context = {
            'visitor': visitor,
            'form': form,
        }
    
    return render(request, 'visitors_card_app/detail.html', context)


def confirm_contact(request, pk):
    visitor = Visitors.objects.get(pk=pk)
    
    form = MemberForm(request.POST)
    if form.is_valid():
        interviewer = form.cleaned_data['member']
    if request.method == 'POST':
        context = {
            'visitor': visitor,
            'interviewer': interviewer,
            'time': request.POST.get('time'),
            'contents': request.POST.get('contents'),
        }
    return render(request, 'visitors_card_app/confirm_contact.html', context)



def sent_contact(request, pk):
    visitor = Visitors.objects.get(pk=pk)
    """
    もしPOSTメソッドならば
    """
    if request.method == 'POST':
        contact = visitor # これ要らない気がすると思って一度消したけど、最後のcreate文で代入してデータベースに登録している。
        interviewer_post_name = request.POST.get('interviewer')
        print(interviewer_post_name)
        target = '/'
        idx = interviewer_post_name.find(target) # target:'/'のindex位置を取得
        interviewer_name = interviewer_post_name[idx+2:] # target:'/'の位置からプラス2した位置から文字列取得
        print(interviewer_name)
        """
        もし名前を何も選ばずに担当者が登録したら
        """
        if interviewer_post_name == "None":
            interviewer = Member.objects.get(name='ダミー')
            visitor.is_contacted = True
            visitor.save()
        else:

visitors_card_dev/visitors_card_app/views/graph_views.py
from django.shortcuts import render
from datetime import datetime, date, timedelta
from dateutil.relativedelta import relativedelta
import calendar
from .. import graph
from ..models import *
import datetime as dt
from django.db.models.functions import TruncDate
from django.db.models import Count
from django.contrib.auth.decorators import login_required

@login_required
def analysis_index(request):
    today = dt.date.today()
    # 今月
    cm_st = today.replace(day=1)
    nm_st = (today + relativedelta(months=1)).replace(day=1)
    cm_ed = nm_st - timedelta(days=1)
    # 今日から一か月の間の日数で日付を取得
    # date_list = [datetime(2020, 1, 25) + timedelta(days=i) for i in range(10)]
    rm_ed = today - relativedelta(months=1)
    date_list = [today - timedelta(days=i) for i in range(30)]
    print('1か月分の日付時刻取得date_list；', end='')
    print(date_list)
    # 1か月後の日付
    print('1か月後の日付時刻取得；', end='')
    print(rm_ed)
    # 先月
    pm_st = (today - relativedelta(months=1)).replace(day=1)
    pm_ed = cm_st - timedelta(days=1)
    print('これまでの日付取得の様子')
    print('今月：{}～{}'.format(cm_st.strftime('%Y/%m/%d'),cm_ed.strftime('%Y/%m/%d')))
    print('先月：{}～{}'.format(pm_st.strftime('%Y/%m/%d'),pm_ed.strftime('%Y/%m/%d')))
    print(calendar.monthrange(cm_st.year, cm_st.month)[1])
    print('今日の日付取得；', end='')
    print(today)
    print('1か月後の日付取得；', end='')
    print(rm_ed)

    # 期間指定来訪者クエリーセット取得
    qs    = Visitors.objects.filter(date__range=(rm_ed, today)).annotate(visited_date=TruncDate('date')).values('date').annotate(count=Count('pk'))  #モデルクラス(ProductAテーブル)読込
    qs_range    = Visitors.objects.filter(date__range=(rm_ed, today))
    if qs and qs_range:
        # qs = Visitors.objects.filter(date__lte=today, date__gte=rm_ed)
        print('1か月間期間指定のクエリーセット：', end='')
        print(qs)
        qs_date_list = []
        for i in qs:
            qs_date_list.append(i['date'])
        print('1か月間期間指定のクエリーセットの日付リストqs_date_list：', end='')
        print(qs_date_list)

        """
        x,yのパラメーター代入
        """
        x     = [x for x in reversed(date_list)]           #X軸データ
        print('リストx reversed(date_list)の出力：', end='')
        print(x)
        # y     = [y.Revenue for y in qs]        #Y軸データ

        qs_date_index = []
        for i in qs_date_list:
            if i in x:
                qs_date_index.append(x.index(i))
        print('qs_date_index：', end='')
        print(qs_date_index)

        y = []
        for i in x:
            if i in qs_date_list:
                print(dir(qs_range))
                qs_per_date = qs_range.filter(date=i)
                y.append(len(qs_per_date))
            else:
                y.append(0)

        print('qs_per_date：', end='')
        print(qs_per_date)
        print(y)
        chart = graph.Plot_Graph(x,y)          #グラフ作成
        
        total = len(qs_range)
        context= {
            'chart': chart,
            'total': total,
        }

        return render(request, 'visitors_card_app/analysis/analysis_index.html', context)
    else:
        return render(request, 'visitors_card_app/analysis/analysis_index.html')

visitors_card_dev/visitors_card_app/templates/visitors_card_app/analysis/analysis_index.html
{% extends 'base.html' %}

{% load static %}
{% block head %}
  <link rel="stylesheet" href="{% static 'css/sidebars.css' %}">
  <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
  <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  {% comment %} ドロップダウンメニューが利かなくなったので下記追加 {% endcomment %}
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
{% endblock %}

{% block title%}集計{%endblock %}
{% block header %}<h1>集計情報</h1>{% endblock %}

{% block content %}
<div class="row">
  <div class="wrapper">
{% include 'visitors_card_app/analysis/sidebar.html' %}


        {% comment %} <div id="content"> {% endcomment %}
            <button type="button" id="sidebarCollapse">
                <span></span>
                <span></span>
                <span></span>
            </button>
          <div class="container">
            <div class="row">
              <div class="col-7">
              {% if total %}
                  <h2>1日当たりの訪問者数　　　　　　　　合計{{ total }}件</h2>
              {% else %}
                  <h2>1日当たりの訪問者数　　　　　　　　未登録</h2>
              {% endif %}
              </div>
                <div class="col-2">
                  <form method="post">
                  {% csrf_token %}
                      <select name="narrow_period">
                        <option value="1month" selected>直近1か月</option>
                        <option value="3months">直近3か月</option>
                        <option value="1month">今月</option>
                        <option value="1month">先々月</option>
                      </select>
                    <button name="go_narrow_period">絞り込み</button>
                  </form>
                </div>
              <div class="col-3">
                <form method="post">
                {% csrf_token %}
                  <select name="period_year">
                    <option value="2022">2022</option>
                    <option value="2021">2021</option>
                    <option value="2020">2020</option>
                  </select>
                  <select name="period_month">
                    <option value="">----</option>
                    <option value="1月">1月</option>
                    <option value="2月">2月</option>
                    <option value="3月">3月</option>
                    <option value="4月">4月</option>
                    <option value="5月">5月</option>
                    <option value="6月">6月</option>
                    <option value="7月">7月</option>
                    <option value="8月">8月</option>
                    <option value="9月">9月</option>
                    <option value="10月">10月</option>
                    <option value="11月">11月</option>
                    <option value="12月">12月</option>
                  </select>
                  <button name="go_specify_period">期間指定</button>
                </form>
              </div>
            </div>
            	<img src="data:image/png;base64,{{ chart | safe }}" alt="1日当たりの訪問者数：データ未登録">
          </div>
        {% comment %} </div> {% endcomment %}
  </div>
</div>
    <!-- jQuery CDN - Slim version (=without AJAX) -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- Popper.JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
<script>
$(document).ready(function () {
    $('#sidebarCollapse').on('click', function () {
        $('#sidebar').toggleClass('active');
        $(this).toggleClass('active');
    });
});


$(function() {
    $('.js-dropdown').click(function(){
        $('.js-dropdown-menu').toggle();
    });
});

$(function() {
    $('.js-dropdown2').click(function(){
        $('.js-dropdown-menu2').toggle();
    });
});













{% comment %} 
$('ul>li>a').on('click', function(){
   
      $('.collapse').collapse('hide');
}); {% endcomment %}
{% comment %} 
$(".js-dropdown").click(function () {
  $(".js-dropdown-menu").slideToggle();
});

$(".js-dropdown").click(function(){
    $(this).toggle();
});

$(".js-dropdown").click(function(){
    $("#dropdown2").hide();
}); {% endcomment %}



{% comment %} 
$(function(){
  var $dropdown = $('.js-dropdown');
  var DURATION = 200; //アニメーションの速さ

  function fadeOutMenu(){
    $dropdown.removeClass('collapse')
      .next('.js-dropdown-menu')
      .stop()
      .slideUp(DURATION);
  }

  //表示を切り替える
  function toggleMenu(){
    var $self = $(this); //thisにはクリックした時の要素が入る
    //要素が.is-activeを持っていない場合
    if(!$self.hasClass('collapse')){
      fadeOutMenu();
    }
    //クリックした要素を表示させる
    $self.toggleClass('collapse')
      .next('.js-dropdown-menu')
      .stop().slideToggle(DURATION);
  }

  $dropdown.on('click', toggleMenu);
 
//別の場所をクリックすると閉じる処理
  $(document).on('click touchend', function(event) {
  if (!$(event.target).closest('body').length) {
    // ここに処理;
    fadeOutMenu();//関数呼びだし
  }
});
}); {% endcomment %}

</script>
{% endblock %}

visitors_card_dev/visitors_card_app/templates/visitors_card_app/analysis/sidebar.html
    <nav id="sidebar">

        <ul class="list-unstyled components">
            <p></p>
            <li>
                <a href="{% url 'visitors_card_app:analysis_index' %}">トップ</a>
            </li>
            <li>
                <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="true" class="dropdown-toggle js-dropdown">カテゴリー</a>
                <div class="js-dropdown-menu">
                <ul class="list-unstyled" id="homeSubmenu">
                    <li>
                        <a href="{% url 'visitors_card_app:list_company' %}">企業</a>
                    </li>
                    <li>
                        <a href="{% url 'visitors_card_app:list_name' %}">訪問者</a>
                    </li>
                    <li>
                        <a href="{% url 'visitors_card_app:list_interviewer' %}">担当者</a>
                    </li>
                    <li>
                        <a href="{% url 'visitors_card_app:list_history' %}">一覧</a>
                    </li>
                    <li>
                        <a href="#">集計情報一覧</a>
                    </li>
                </ul>
                </div>
            </li>
            {% comment %} <li>
                <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle js-dropdown2">期間</a>
                <div class="js-dropdown-menu2">
                <ul class="list-unstyled" id="pageSubmenu" style="collapse: hide;">
                    <li>
                        <a href="#">年毎</a>
                    </li>
                    <li>
                        <a href="#">月毎</a>
                    </li>
                </ul>
                </div>
            </li> {% endcomment %}
        </ul>
    </nav>